#!/usr/bin/python

import sys
import os
import json

__version__ = 1.0
__author__ = 'tao'

home_dir = os.path.expanduser('~')
db_file = '.telp.json'
db_path = os.path.join(home_dir, db_file)

telp_dict = {}


def init():
    if not os.path.exists(db_path):
        with open(db_path, 'w+') as f:
            print('initialize complete')
        return
    with open(db_path, 'r') as f:
        content = f.read()
        try:
            telp_dict.update(json.loads(content))
        except:
            pass


def usage():
    print('telp usage:\n')
    print('$telp command-keyword "command model"')
    print('   save the command model to the telp')
    print('$telp command-keyword')
    print('   show command models related to the command-keyword')


def print_telp():
    spoon = sys.argv[1]
    not_found = ['telp "{}" not found'.format(spoon)]
    telps = telp_dict.get(spoon, not_found)
    for i, h in enumerate(telps):
        print(h)


def save_telp():
    print('telp saved')
    spoon = sys.argv[1]
    telp_dict[spoon] = telp_dict.get(spoon, []) + sys.argv[2:]
    with open(db_path, 'w') as f:
        f.write(json.dumps(telp_dict, indent=2))


def main():
    argc = len(sys.argv)
    actions = {
        2: print_telp,
        3: save_telp,
    }
    action = actions.get(argc, usage)
    action()


if __name__ == '__main__':
    init()
    main()
