# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH:/usr/local/mysql/bin

# Path to your oh-my-zsh installation.
export ZSH=/Users/zhanghe/.oh-my-zsh

ZSH_THEME="ys"

# #### use the following command to install `zsh-syntax-highlighting` plugin ####

# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting 
plugins=(git z extract colorize history-substring-search zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# python virtualenvs
# pip3 install virtualenv virtualenvwrapper
# mkdir ~/.virtualenvs
# virtualenvwrapper
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3 
export WORKON_HOME=~/.virtualenvs 
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh 
[ -f /etc/bash_completion.d/virtualenvwrapper ] && source /etc/bash_completion.d/virtualenvwrapper 
export PIP_VIRTUALENV_BASE=$WORKON_HOME 
export PIP_RESPECT_VIRTUALENV=true


# alias
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias h='history'
alias ll="ls -lh"
alias la="ls -ha"
alias lla="ls -lha"
alias cls="clear"
alias rm="rm --help"
# alias rm="rm -i"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"

alias g="git add -A"
alias gg="git add -A && git commit"
alias ggg="git add -A && git commit && git push"

alias ipy="ipython"
alias bpy="bpython"
alias py="python"
alias py3="python3"

alias vte='virtualenv'                                                                                                                       
alias wkon="workon"
alias mkvte='mkvirtualenv'                                                                                                                   
alias deact='deactivate'                                                                                                                     
alias rmvte='rmvirtualenv'
alias lsvte="lsvirtualenv"
alias tree="tree -NC" 
# alias dkr=docker
# alias b2d=boot2docker-cli
# alias vbm=VBoxManage
# alias airport="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"
# alias ssh="TERM=xterm-256color ssh"
